# Adapted from: https://blog.logrocket.com/containerized-development-nestjs-docker/
# and: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/

# Standalone dashboard docker build (no api required)
# $docker build -f docker/DOCKERFILE --tag chrismclarke/odkx-dashboard .
# $docker run -p 80:80 --name odkxm --rm chrismclarke/odkx-dashboard

### STAGE 1: Build ###
FROM node:12-alpine AS build
# Set working directory
WORKDIR /usr/src/app
# Add node_modules to path
ENV PATH="./node_modules/.bin:$PATH"
# Copy dependency files to allow caching
ADD package.json ./
ADD yarn.lock ./
# Skip standard postinstall as this will be completed in next step
RUN yarn install --ignore-scripts
# Angular post-install optimisation
RUN ngcc
# Copy rest of app files
ADD . .
# Copy hardcoded config (can be bound later)
RUN cp ./docker/dashboard.config.json ./apps/dashboard/src/assets/dashboard.config.json

# Build the dashboard with docker env as specified in src/environments (no api proxy)
# Assumes it will be served on proxy /dashboard
RUN ["nx", "build","dashboard","--configuration=docker","--base-href=/dashboard/"]

### STAGE 2: Serve Dashboard ###
FROM nginx:1.17-alpine
# COPY nginx.config /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/dist/apps/dashboard /usr/share/nginx/html
# Run the nginx server
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
