name: Docker Publish Production
on:
  release:
    types: [published]
jobs:
  docker_build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/metcalfc/docker-action-examples/blob/main/.github/workflows/release.yml
      - name: prep tags
        id: prep
        run: |
          DOCKER_IMAGE=chrismclarke/odkx-dashboard
          APP_VERSION=$(echo "$(cat package.json | jq -r '.version')")
          TAGS="${DOCKER_IMAGE}:${APP_VERSION},${DOCKER_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
      - name: check_tags
        run: echo "tags - ${{ steps.prep.outputs.tags }}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/DOCKERFILE
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=registry,ref=chrismclarke/odkx-dashboard:latest
          cache-to: type=inline
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
